### PR TITLE
Bail out if stateProps can be calculated early and did not change

### LINKED ISSUE #1437: Dispatch more than once in non-batched update cause incorrect result with `useSelector`
**Do you want to request a _feature_ or report a _bug_?**

Report a bug.

**What is the current behavior?**

I'v created a reproducing repo here https://github.com/malash/react-redux-issue-ref/blob/master/reduxBug.js

This repo use both `react-redux` and `react-native`. 
```jsx
<Button
  title="[BUG] Click Me (setTimeout)"
  onPress={() => {
    setTimeout(() => {
      dispatch({type: 'NOOP'});
      dispatch({type: 'TOGGLE'});
    }, 0);
  }}
/>
```

When using `setTimeout`'s callback to dispatch multi times, the `useSelector` return incorrect value. The reason why I use `setTimeout` is to ensure these dispatch calling are non-batched.

```jsx
const selector = state => ({
	bool: state.bool,
});

const ReduxBugParent = () => {
  const {bool} = useSelector(selector);
  // ...
  <Text>bool from useSelector is {JSON.stringify(bool)}</Text>
  <Text>bool from store.getState is {JSON.stringify(boolFromStore)}</Text>
}
```

After click the button different selector result are shown. the `bool` are always different with `boolFromStore`.

Screen Recording 2019-10-29 at 11 05 55 PM

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:**

1. Clone the repo https://github.com/malash/react-redux-issue-ref
2. [Install React Native CLI](https://facebook.github.io/react-native/docs/getting-started)
3. Run `react-native run-ios`
4. Click buttons and see rendered values.

**What is the expected behavior?**

This bug can only reproduce on non-web environment, maybe it is related to https://github.com/reduxjs/react-redux/issues/1436

I believe it should works on React Native as well as React DOM.

**Which versions of React, ReactDOM/React Native, Redux, and React Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React Redux?**

react@16.9.0
react-native@0.61.2
react-redux@7.1.1
redux@4.0.4

**cc**

@byunicorn

### PR DESCRIPTION
**Pull request by gaearon**
This should fix https://github.com/reactjs/redux/issues/1437 and #300.

If the component doesn’t care about `ownProps`, we can bail out of calling `setState()`.
This PR implements this optimization.

As a reminder, we can’t do this for components that *do* care about `ownProps` due to #99.

----------------

Above, I said:

>As a reminder, we can’t do this for components that *do* care about `ownProps` due to #99.

*However* in many cases it’s possible to convert a component that needs `ownProps` to a component that doesn’t.

How? In #279, we added the ability to specify factories instead of `mapStateToProps` and `mapDispatchToProps`. Curiously, these factories *themselves* do receive `state` and `ownProps` as arguments. Of course, they are only invoked once, **but if you’re only using `ownProps` to read an ID** (which is a common case in large lists) and use stable `key`s, you should be able to change

```js
function mapStateToProps(state, ownProps) {
  return {
    item: state.items[ownProps.id]
  }
}
```

into

```js
function makeMapStateToProps(initialState, initialOwnProps) {
  var id = initialOwnProps.id
  return function mapStateToProps(state) {
    return {
      item: state.items[id]
    }
  }
}
```

See? Obviously `id` would never get updated, but we don’t need it to (in this particular case). And we can always add `ownProps` later (of course at the performance cost).

I think it’s a neat trick, and it will benefit from merging this optimization, since this optimization is relevant to any `mapStateToProps` that doesn’t depend on `ownProps`.

### CODE REVIEW

**Comment by gaearon** [comment]
cc @slorber, @ellbee, @tgriesser who might be interested in this

**Comment by ellbee** [comment]
This one looks like a clear win to me, but I wonder if it would be worth working on a benchmark suite again like the one started in #104? I've used benchmark.js before, but not for testing UI code. Is it even really feasible?

**Comment by gaearon** [comment]
For now, I’m testing against https://github.com/mweststrate/redux-todomvc manually.
My work in progress on optimizing app itself to Redux patterns is in https://github.com/mweststrate/redux-todomvc/pull/1.

**Comment by ellbee** [comment]
Yeah, I have just been reading through that issue. It is what made me start thinking about it. I might have a play around with it.

**Comment by gaearon** [comment]
:+1:

**Comment by gaearon** [comment]
Oh wait, I’m supposed to emoji your post inline.

**Comment by slorber** [comment]
@gaearon this is great news that connect not using component's props get faster :)

However I'm not sure the current implementation is the best we could do:

- The factory method works but is kind of unintuitive API at first
- If a connected component do care about ownProps, and these props can change (ie can't use the factory), then the component will setState even if the props don't change often


Instead of 

```javascript
function makeMapStateToProps(initialState, initialOwnProps) {
  var id = initialOwnProps.id
  return function mapStateToProps(state) {
    return {
      item: state.items[id]
    }
  }
}

connect(makeMapStateToProps)(Component)
```

I would rather have something like:


```javascript
connect({
   mapperPropsSelector: ownProps => {id: ownProps.id},
   mapper: (state,{id}) => state.items[id]
})(Component)
```

(this is probably not the best API but you get the idea)

What it permits here is to make it clear on what the mapping function has to rely on to do its job, so you can more easily detect when props needed for the mapping have changed and run the mapper only when needed


And I think, by default, not providing any ownProps to the mapping function (ie no selector provided) would actually encourage people to write more optimized code by default (unlike factories which would be opt-in optimization), but it would be a breaking change


(This is related to my proposal  for more flexible subscriptions here: https://github.com/reactjs/react-redux/issues/269#issuecomment-175904958)

**Comment by gaearon** [comment]
I’m confused: how does accepting a selector for props solve the problem of `setState()`? As soon as something depends on `ownProps`, due to #99, we are forced to delay its calls until `render()` at which point we have already paid the price of `setState()`.

**Comment by timbur** [comment]
Sorry if I'm going on a tangent with this comment but I'll share some performance optimizations I implemented earlier this month when I rewrote [`react-redux-provide`](https://github.com/loggur/react-redux-provide).  These optimizations might not perfectly translate to `react-redux` but perhaps similar algorithms could be implemented.

I added a `watch` method to the store which accepts a `reducerKey` and a `callback` function to be called whenever the reducer returns a different state (via a reducer enhancer).  The declarative nature of `react-redux-provide` makes it possible to automatically efficiently watch for changes to the relevant reducers, and in which case, a `doUpdate` flag is raised so than we can simply call `forceUpdate` after the action has completed, since we already know some relevant state has changed.  The wrapped component's props are cached and updated accordingly per reducer.  This means no need for shallow comparisons or loops, and `shouldComponentUpdate` can always return false (unless the component receives new props of its own, of course).  And so updates should be near instantaneous as they, in theory, only require a few clock cycles per relevant component - i.e., new state -> relevant components -> update.

Condensed version:
```js
for (let reducerKey of reducerKeys) {
  this.unsubscribe.push(
    store.watch(                  // when some reducer returns a new state
      reducerKey, nextState => {  // update wrapped component's props
        this.componentProps[reducerKey] = nextState;
        this.doUpdate = true;     // and we know for sure we should update
      }
    )
  );
}

this.unsubscribe.push(
  store.subscribe(() => {         // after action has completed
    if (this.doUpdate) {          // simply check for doUpdate flag
      this.forceUpdate();
    }
  })
);
```

See the full version where the same method is used for props derived from some combination of state and own props:
https://github.com/loggur/react-redux-provide/blob/master/src/provide.js#L93-L212

To elaborate a little bit more, deriving props from a combination of state and own props looks like this:
```js
// here we'll provide some item within a list
const merge = {
  item: {           // this is run only for components with an `item` propType
    keys: ['list'], // the provided `item` depends on the state of the `list`
    get(state, props, context) {
      // this function is executed only when `list` changes
      // and components will be updated only when the `item` has changed
      const { list } = state;
      const { itemIndex } = props;

      return list[itemIndex] || null;
    }
  }
};
```

Performance tests are coincidentally next on my todo list.  I was planning on seeing how things perform when incorporated into [`dbmon`](https://github.com/ryanflorence/reactconf-2015-HYPE/tree/master/demos/01-dbmon), but I think I'll also run some benchmarks on [`react-redux-provide/examples/todomvc`](https://github.com/loggur/react-redux-provide/tree/master/examples/todomvc).

**Comment by slorber** [comment]
> I’m confused: how does accepting a selector for props solve the problem of setState()? As soon as something depends on ownProps, due to #99, we are forced to delay its calls until render() at which point we have already paid the price of setState().

@gaearon sorry it's hard to think well on such code late in the night :) My proposal may not prevent the `setState` cost finally.

The problem I see with current code is that for example if this component changes from

```javascript
<Todo id={123} className="someName"/>
```

 to 

```javascript
<Todo id={123} className="anotherClassName"/>
```

then yes we necessarily have to do a `setState` because ownProps have changed and we must render the child. The problem is that here our `mapStateToProps` is relying on ownProps but actually does only care about the `id`, and not `className`.

This line:

```javascript
shouldUpdateStateProps = hasStoreStateChanged || (
            haveOwnPropsChanged && this.doStatePropsDependOnOwnProps
          )
```

it will make `mapStateToProps` be run in such a case, while it could have been avoided if we could have known that `mapStateToProps` is not interested to receive the `className` property but only the Todo id.


Also, not a big deal, but not sure `this.doStatePropsDependOnOwnProps = this.finalMapStateToProps.length !== 1` is relyable if someone writes mapStateToProps with `arguments[0]` (yes it is unlikely... :p)

**Comment by joonhyublee** [comment]
@gaearon Here is [my use case](https://github.com/yelouafi/redux-saga/issues/241#issuecomment-207202589), in which early bailout yields significant performance boost.

With regards to @slorber's concern that props *can* change, I encountered a similar issue, and I did this hack to get around it.

Let's say we have:
```javascript
//factory for map state to props, as per Dan's suggestion above
const makeMapStateToProps = (initialState, initialProps) => {
  const { userID } = initialProps; //props that's not expected to change (often)

  const mapStateToProps = (state) => {
    const userNickname = state.users[userID].nickname; //slice of state dependent on props
    const userAvatar = state.users[userID].avatar; //slice of state dependent on props

    return {
      userNickname,
      userAvatar
    };
  };

  return mapStateToProps;
}

const UserComponent = React.createClass({
  // component implementation
});

export default connect(makeMapStateToProps)(UserComponent);
```
Of course, userID isn't expected to change, but there may be some cases where it does. For example, the above component may be a react-router route component, which gets its userID from the pathname: `http://example.com/userpage/cat`. When the path changes to `http://example.com/userpage/dog` the component holds on to stale userID (cat) and this causes problems. (because react router doesn't re-mount for the same route)

I *could* revert back to `mapStateToProps (state, ownProps)`, but I would loose the performance boost gained from the early bailout. So instead, I do this:

```javascript
//instead of this,
export default connect(makeMapStateToProps)(UserComponent);

//do this:
const ConnectedComponent = connect(makeMapStateToProps)(UserComponent);
export default (props) => (
  <ConnectedComponent key={ props.userID }/>
);
```
Because of key, when userID is changed, the old component is completely unmounted, and new one is mounted instead, with the updated props. It's a bit hacky, but I think this is an acceptable trade-off. I guess for multiple props that aren't expected to change often I can stringify as a key:
```javascript
export default (props) => (
  <ConnectedComponent key={ props.userID + '_' + props.anotherSparselyChangedProp }/>
);
```
but that .. is beyond ugly. It does bother me there are so many different steps within different levels involved in simply invalidating and updating a component, but was the only way I could make this work.

**Comment by slorber** [comment]
nice trick @joonhyublee :D 

Maybe this usecase will be easier to handle once the code of connect becomes much simpler, and it might with https://github.com/reactjs/react-redux/issues/368

**Pull request merged**
