### PR TITLE
Fix deprecation warnings for react >= 15.5.0

### PR DESCRIPTION
**Pull request by Calyhre**
Migrate `React.PropTypes` to `PropTypes` from the `prop-types` package, regarding the latest `react` version -> https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

### CODE REVIEW

**Comment by jimbolla** [comment]
Does this work if someone is still targeting React 14?

**Comment by wojtekmaj** [comment]
It should. PropTypes were not wildly modified since then.

**Comment by gaearon** [comment]
It should work. But I'm not sure if putting it in dependencies would be better.

**Comment by gaearon** [comment]
Yes, lets change this to use dependencies instead.

**Comment by Calyhre** [comment]
Ok :) I moved it from devDependencies to dependencies, and drop the line for peers.

**Comment by gaearon** [comment]
We probably don't need Yarn lock? Seems unrelated to this PR.

**Comment by Calyhre** [comment]
👍  yarn.lock modifications removed

**Comment by timdorr** [comment]
Yes, you do. yarn.lock files are updated with every PR that modifies the dependencies. It's the same for other systems that use lock files (e.g., rubygems)

**Comment by timdorr** [comment]
Thanks, @Calyhre. I've got some follow-on fixes for the tests and to put the lock file back. I'll add those after I merge this in. Thanks!

**Comment by gaearon** [comment]
>Yes, you do. yarn.lock files are updated with every PR that modifies the dependencies

Oops, pardon the brainfart. I don't really understand why I said that 😛

**Comment by gaearon** [comment]
@Calyhre Would you like to also send a PR to backport this to 4.x

**Comment by timdorr** [comment]
Just pushed out 5.0.4 with this. Thanks!

**Comment by lama-pacos** [comment]
old react version will warning
…………

**Comment by gaearon** [comment]
Yes, we’re discussing this in https://github.com/reactjs/react-redux/issues/669.

**Comment by gaearon** [comment]
I released `react@0.14.9` and `react-dom@0.14.9`, they won’t have the warning.

**Pull request merged**
