### PR TITLE
Add additional optional function to the connect function that allows using react-redux without the Provider class

### PR DESCRIPTION
**Pull request by challenger532**

### CODE REVIEW

**Comment by challenger532** [comment]
is there any thing I can do to accept this pull request ?

**Comment by jimbolla** [comment]
You can already use connect without Provider by passing the store as a prop. You can leverage https://github.com/acdlite/recompose to build the functionality you want in userland. Basically this:

customconnect.js:
```js
import { connect } from 'react-redux'
import { compose, withPropsOnChange } from 'recompose'

const customConnect = (mapState, mapDispatch, options, storeProvider) => compose(
  withPropsOnChange(
    () => false,
    () => ({ store: storeProvider.getStore() })
  ),
  connect(mapState, mapDispatch, options)
);

export default customConnect;
```

**Comment by markerikson** [comment]
Yeah, I'm not clear on what this actually does, or what the real benefit is.

**Comment by timdorr** [comment]
Yeah, we've already got this functionality another way. Thanks anyways!

**Pull request closed without merging**
