### PR TITLE
Allow React 16 as peerDependency for 4.x

### PR DESCRIPTION
**Pull request by gaearon**
This is currently causing warnings in our React Native builds at Facebook.
Could you please merge this and release a bump?

I could do this myself but I haven't released in a while and don't want to screw up 😛

### CODE REVIEW

**Comment by timdorr** [comment]
Yep, no problem.

**Comment by timdorr** [comment]
Oh wait, this is for 4.0. Did those teams run into problems moving to 5.0? I know that might be a bigger ask, but BC should be maintained despite the major bump.

**Comment by timdorr** [comment]
Pushed as 4.4.7

**Comment by gaearon** [comment]
I don't think we're using 5.x anywhere yet, will raise issues if we find problems.

**Pull request merged**
