### PR TITLE
Fixes #582 (Nested Provider subscriptions)

### LINKED ISSUE #582: mapStateToProps not always called after upgrading to 5.0.1
I have a boolean value inside a reducer and the `mapStateToProps` is not always called when the value changes.

Here's the log from 4.4.6:
```
[mapStateToProps] showResults false
[reducer] previous value: false ; new value: true
[mapStateToProps] showResults true
[reducer] previous value: true ; new value: false
[mapStateToProps] showResults false
```

But here's the one from 5.0.1:
```
[mapStateToProps] showResults false
[reducer] previous value: false ; new value: true
[mapStateToProps] showResults true
[reducer] previous value: true ; new value: false
[reducer] previous value: false ; new value: false
```

### PR DESCRIPTION
**Pull request by jimbolla**

### CODE REVIEW

**Comment by ZhengHe-MD** [comment]
thx..i just got into this problem. That's awesome

**Comment by ZhengHe-MD** [comment]
and when will next patch be released? I need this in my project😅😍

**Comment by jimbolla** [comment]
@timdorr Any thoughts on pushing out a patch release?

**Comment by timdorr** [comment]
Sorry, I've been dealing with a house full of sick people (myself included). I'll try to get something out soon-ish.

**Pull request merged**
