### PR TITLE
Adds support for react 15.0.0-rc.2 to peer-dependencies

### PR DESCRIPTION
**Pull request by mil**

### CODE REVIEW

**Comment by gaearon** [comment]
Thanks for the PR but `^15.0.0-rc.1` already matches `^15.0.0-rc.2` (and will match `15.x` as well).
You can verify this with the [semver calculator](http://semver.npmjs.com/).
Cheers!

**Comment by antoinerousseau** [comment]
`^15.0.0-rc.1` does not match current version (`15.0.1`)

    $ npm i --save react@15
    npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer react-redux@4.4.1 wants react@^0.14.0 || ^15.0.0-rc.1

**Comment by gaearon** [comment]
It does match. Please verify on a clean project. Unfortunately npm prints *all* dependencies in this error message rather than the ones causing the issue. I just verified that even with npm@2, both `^15.0.0-rc.1` will match stable versions:

```
dan@home ~/p/justtestingnpm> npm -v
2.11.0
dan@home ~/p/justtestingnpm> npm i --save react-redux@4.4.2 react@15.0.1 redux@3.4.0
npm WARN package.json justtestingnpm@1.0.0 No description
npm WARN package.json justtestingnpm@1.0.0 No repository field.
npm WARN package.json justtestingnpm@1.0.0 No README data
redux@3.4.0 node_modules/redux
├── loose-envify@1.1.0 (js-tokens@1.0.3)
├── lodash-es@4.9.0
└── lodash@4.9.0

react-redux@4.4.2 node_modules/react-redux
├── invariant@2.2.1
├── hoist-non-react-statics@1.0.5
├── loose-envify@1.1.0 (js-tokens@1.0.3)
└── lodash@4.9.0

react@15.0.1 node_modules/react
├── object-assign@4.0.1
├── loose-envify@1.1.0 (js-tokens@1.0.3)
└── fbjs@0.8.0 (ua-parser-js@0.7.10, promise@7.1.1, babel-plugin-syntax-flow@6.5.0, core-js@1.2.6, isomorphic-fetch@2.2.1)




npm i --save react-redux@4.4.1 react@15.0.1 redux@3.4.0
npm WARN package.json justtestingnpm@1.0.0 No description
npm WARN package.json justtestingnpm@1.0.0 No repository field.
npm WARN package.json justtestingnpm@1.0.0 No README data
redux@3.4.0 node_modules/redux
├── loose-envify@1.1.0 (js-tokens@1.0.3)
├── lodash-es@4.9.0
└── lodash@4.9.0

react-redux@4.4.1 node_modules/react-redux
├── invariant@2.2.1
├── hoist-non-react-statics@1.0.5
├── loose-envify@1.1.0 (js-tokens@1.0.3)
└── lodash@4.9.0

react@15.0.1 node_modules/react
├── object-assign@4.0.1
├── loose-envify@1.1.0 (js-tokens@1.0.3)
└── fbjs@0.8.0 (ua-parser-js@0.7.10, promise@7.1.1, babel-plugin-syntax-flow@6.5.0, core-js@1.2.6, isomorphic-fetch@2.2.1)
```

**Comment by antoinerousseau** [comment]
OK well I updated to NPM 3 and the issue went away. Thanks anyway for your answer!

**Comment by gaearon** [comment]
No problem. Sorry npm 2.x is weird  ¯\_(ツ)_/¯

**Pull request closed without merging**
