### PR TITLE
Added support to react@15.0.0-rc.1

### PR DESCRIPTION
**Pull request by chentsulin**

### CODE REVIEW

**Comment by istarkov** [comment]
Isn't the same must be done for `devDependencies` except `||`

**Comment by jslauthor** [comment]
I would love to see this happen immediately. :smile:

**Comment by gaearon** [comment]
For the future reference, you can use `npm@3.x` in which peer dependency mismatch is a warning rather than a hard error.

>Isn't the same must be done for devDependencies except ||

When 15.0 comes out, we’ll upgrade them. For now let’s run tests on the stable version.

**Comment by gaearon** [comment]
Out in 4.4.1, thanks!

**Pull request merged**
