### PR TITLE
Copy build steps from redux. Fixes #243

### LINKED ISSUE #243: jsmain:next should point to a “redistributable ES2015 bundle”
what that means is “syntax the platform (browser/node) can read except for the ES2015 import/export syntax”

funnily my test project doesn’t work with specifically react-redux:

* <code>rollup([babel](https://github.com/rollup/rollup-plugin-babel)(), [commonjs](https://github.com/rollup/rollup-plugin-commonjs)(), [npm](https://github.com/rollup/rollup-plugin-npm)({'jsnext:main': true}))</code> → rollup’s acon can’t parse the object spread syntax [here](https://github.com/rackt/react-redux/blob/master/src/components/connect.js#L12)
* `'jsnext:main': false` → https://github.com/rollup/rollup-plugin-commonjs/issues/29

cc @Rich-Harris @TrySound @Victorystick

### PR DESCRIPTION
**Pull request by btd**

### CODE REVIEW

**Comment by timdorr** [comment]
Can you rebase against `next`? Let's take this on with the next major so that webpack 2 and rollup users don't get into trouble with a minor or patch release.

**Comment by btd** [comment]
@timdorr ok, but can it be in both branches? I just want to get this published sooner than later.

**Comment by timdorr** [comment]
Technically, it's an API change, so it has to go in the next major anyways.

**Comment by btd** [comment]
Could you please explain why it is API change? in npm module will appear just one new folder, everything else byte to byte the same.

**Comment by timdorr** [comment]
It's an API change in the sense that the `main` or `jsnext:main` is an API to access the module. Basically, someone using Rollup or Webpack 2 would experience a breakage if they upgraded just a patch or minor release, which technically violates semver. It's a little loose, I know, but it's important to end users not to upset them and get vague gripes about "fatigue" 😄

**Comment by btd** [comment]
Well, fair enough :+1:. I will rebase to next branch.

**Pull request closed without merging**
