### PR TITLE
Also attempt to exit early when iterating b's keys in shallowEqual

### PR DESCRIPTION
**Pull request by jcready**
[Prior conversation](https://github.com/reactjs/react-redux/pull/416#pullrequestreview-12930768)

### CODE REVIEW

**Comment by jimbolla** [comment]
Can you run some perf benchmarks just to be sure it's faster? You know that old saying about what happens when you ASSUME.

**Comment by appden** [comment]
I'm more concerned of the correctness of `shallowEqual` in `react-redux`. There are a few subtle ways it could fail right now. I think it would be best to copy [`shallowEqual` from `fbjs`](https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/core/shallowEqual.js).

**Comment by jcready** [comment]
I agree with @appden here. For instance `shallowEqual` in react-redux doesn't account for `NaN`. If an object contained any `NaN` value then `shallowEqual` would always return `false`.

**Comment by timdorr** [comment]
I'm going to close this out and we can switch over to the fbjs version. It seems to cover more edge cases and might even be faster in common cases for react-redux.

**Pull request closed without merging**
