### PR TITLE
Upgrade React 15 peerDependency to stable (15.0.1)

### PR DESCRIPTION
**Pull request by antoinerousseau**
Current issue:

```
$ npm i --save react@15

npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' 
peerDependencies requirements!
npm ERR! peerinvalid Peer react-redux@4.4.1 wants react@^0.14.0 || ^15.0.0-rc.1
```

### CODE REVIEW

**Comment by gaearon** [comment]
The current range matches any 15.x release including `15.0.1`.
Please refer to the official [npm semver calculator](http://semver.npmjs.com/):

screen shot 2016-04-09 at 00 08 58

You probably have issue due to some other package. npm just prints all of them rather than the one causing the problem, which is the common source of confusion.

**Comment by antoinerousseau** [comment]
Updated from NPM 2 to NPM 3 and this issue disappeared.

**Comment by gaearon** [comment]
Hmm, weird. Could npm@2 have different behavior?

**Comment by gaearon** [comment]
Are you sure this wasn’t an issue due to any other dependency?

**Comment by antoinerousseau** [comment]
Well the error message is pretty explicit to me... here is the full output I got:

```
$ npm i --save react@15
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save" "react@15"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer draft-js@0.3.0 wants react@^0.14.0 || ^15.0.0-rc
npm ERR! peerinvalid Peer material-ui@0.15.0-alpha.2 wants react@^0.14.0
npm ERR! peerinvalid Peer react-big-calendar@0.9.8 wants react@^0.14.0-beta1
npm ERR! peerinvalid Peer react-dnd@2.1.4 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-intl@2.0.0-rc-1 wants react@^0.14.0 || ^15.0.0-rc.1
npm ERR! peerinvalid Peer react-redux@4.4.1 wants react@^0.14.0 || ^15.0.0-rc.1
npm ERR! peerinvalid Peer react-tap-event-plugin@0.2.2 wants react@^0.14.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/antoine/Sites/mytribe-app/npm-debug.log
```

I read 
> The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!

followed by 
> react-redux@4.4.1 wants react@^0.14.0 || ^15.0.0-rc.1

Which to me means that `react@^0.14.0 || ^15.0.0-rc.1` does not match `react@15.0.1`, but I could be wrong...

**Comment by gaearon** [comment]
Yeah, this is why I said above:

>You probably have issue due to some other package. npm just prints all of them rather than the one causing the problem, which is the common source of confusion.

The reason peer dependency check failed are these packages:

>npm ERR! peerinvalid Peer react-big-calendar@0.9.8 wants react@^0.14.0-beta1
>npm ERR! peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8
>npm ERR! peerinvalid Peer material-ui@0.15.0-alpha.2 wants react@^0.14.0
>npm ERR! peerinvalid Peer react-tap-event-plugin@0.2.2 wants react@^0.14.0

The rest are fine, and once you fix those packages, the other lines won’t be there either. I know this is super confusing but that’s just the way npm@2.x works. I also verified it specifically here: https://github.com/reactjs/react-redux/pull/332#issuecomment-207647393

**Pull request closed without merging**
