### PR TITLE
Fixes subscription bug when a new store is passed as a prop.

### PR DESCRIPTION
**Pull request by jimbolla**
Reported here: https://github.com/davidkpiano/react-redux-form/issues/592

### CODE REVIEW

**Comment by davidkpiano** [comment]
Thanks @jimbolla  - the general idea is that this should work:

```jsx
// overly simplified for clarity

<Provider store={store}>
  <Foo>
    <Bar store={ownStore} />
  </Foo>
</Provider>
```

If I'm not mistaken, `<Bar>` should subscribe to its `ownStore` as if it were its own `<Provider>` (because it essentially is) instead of depending on parent subscriptions.

**Comment by jimbolla** [comment]
Correct. I think there's an edge case to this edge case I'm not covering so I'm gonna keep working on it, but this should be better.

**Comment by jimbolla** [comment]
OK. Now I think I covered the edge cases correctly.

**Comment by jimbolla** [comment]
@timdorr Thoughts on pushing a patch release for this and the other handful of fixes we have waiting to go out?

**Comment by jimbolla** [comment]
I added an extra safeguard in here as well that I'm pretty sure will also fix #588 but I don't have an exact repro for that one, so I'm approximating.

**Comment by davidkpiano** [comment]
Any updates on this? Will it be able to be merged in soon? 🙏

**Comment by markerikson** [comment]
@jimbolla , @timdorr : following up on this at @davidkpiano 's request.  It's Jim's code thus far, and Tim's been cutting releases (something I should go figure out for myself at some point, but don't have time to dig into atm).  Are we good to go on this?

**Comment by timdorr** [comment]
I haven't had time to really dig into this one. It's a non-trivial change, hence the hesitation to just blindly merge it in. If anyone else wants to review, I trust them to point out any problems.

**Comment by markerikson** [comment]
Yeah, that's actually how I feel about this myself at the moment :)

**Comment by jimbolla** [comment]
@timdorr @markerikson It might be easier to review the 2 commits separately. The bugfix one is pretty small and the refactor one just moves a few things and adds some more comments.

**Comment by timdorr** [comment]
OK, LGTM. In the future, I'd submit refactors as either separate PRs or just directly onto master.

**Comment by anru** [comment]
@timdorr please release this fix

**Comment by BerndWessels** [comment]
@timdorr The `react-redux 5.0.3` update breaks HMR with latest `react-hot-loader 3.0.0-beta.6`.

Basically after a hot-reload the state is somehow broken.

This worked fine in `react-redux 5.0.2` :(

**Pull request merged**
